### PR TITLE
Create go module, fix permission issue

### PR DESCRIPTION
**Pull request by malacourse**
I created the go module based on the namespaces operator.  You can run locally in the same manor.  Fixed the permission issue with finalizer.

### CODE REVIEW

**Comment by raffaelespazzoli** [comment]
@malacourse as you can probably see the automated buil is failing. It's probably related to the go version bump and or the migration to go modules. please check the `make` file and the `travis.yaml`

**Comment by raffaelespazzoli** [comment]
@sabre1041 the build is successful, so why is the travis check still failing?
@malacourse if it's not too much to ask can you upgrade to go 1.13?

**Comment by sabre1041** [comment]
@raffaelespazzoli The way the environment variables are defined is not correct. It spins up separate jobs for each one instead of one job containing both variables. You should use the `global` environment variable as described [here](https://docs.travis-ci.com/user/environment-variables/#global-variables)

**Comment by raffaelespazzoli** [comment]
@malacourse based on @sabre1041 feedback it looks like it shoud be
```
global:
  env:
    - GO111MODULE=on
```

also removed the DEP_VERSION variable.

Weird though my other projects work without the global thing...: https://github.com/redhat-cop/namespace-configuration-operator/blob/master/.travis.yml

**Pull request merged**
